version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: leadscrape
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: leadscrape
      MINIO_ROOT_PASSWORD: leadscrape123
    command: server /data --console-address ":9001"

  backend:
    build: ../backend
    ports: ["3000:3000"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/leadscrape
      REDIS_URL: redis://redis:6379
      JWT_SECRET: leadscrape-dev-secret
    depends_on: [postgres, redis]
    volumes:
      - ../backend:/app
      - /app/node_modules

  worker:
    build: ../worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/leadscrape
      REDIS_URL: redis://redis:6379
    depends_on: [postgres, redis]
    volumes:
      - ../worker:/app
      - /app/node_modules

volumes:
  postgres_data:
