name: Build & Deploy
on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: lead-backend
  IMAGE_WORKER: lead-worker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }} ./backend
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      - name: Build and push worker
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_WORKER }}:${{ github.sha }} ./worker
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_WORKER }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to cluster
        run: |
          kubectl set image deployment/backend backend=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }}
          kubectl set image deployment/worker worker=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_WORKER }}:${{ github.sha }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
